services:
  freeswitch:
    container_name: freeswitch
    image: praekeltfoundation/freeswitch:1.6.20
    network_mode: "host"
    mem_limit: 1g # per simulare l'attacco DoS
  
  attacker:
    container_name: attacker
    build: ./attacker
    image: attacker
    command: /bin/sh
    tty: true
    depends_on:
    - freeswitch
    volumes:
      - ./attacker/spoofing.py:/spoofing.py
      - ./attacker/dos-sipflood.py:/dos-sipflood.py