services:
  kamailio:
    build: ./kamailio
    image: kamailio
    container_name: kamailio
    network_mode: "host"

  sipp101:
    container_name: sipp101
    build: ./sipp
    image: sipp101
    tty: true
    depends_on:
      - kamailio
    volumes:
      - ./sipp/xml/registration101.xml:/sipp/xml/registration101.xml
      - ./sipp/xml/call102.xml:/sipp/xml/call102.xml
      - ./sipp/xml/overflow.xml:/sipp/xml/overflow.xml
    command: -sn uas