services:
  ndoninja:
    container_name: vdoninja
    build: ./vdoninja
    network_mode: "host"

  node:
    container_name: node
    build: ./node
    tty: true
    volumes:
      - ./node:/node:ro
    command: ["node", "node/server.js"]
    network_mode: "host"
